
"""
Takes a path to the logs generated by an experimental PalRUP run (as 
orchastrated by Mallob's 'palrup-sequence' option) and creates a CSV 
(containing commonly accessed data for each instance) per executed 
PalRUP job, found in the directory. The created CSV is named 
'qresult.csv' and created in the given directory.
"""

import sys
import glob
import copy
import pandas as pd
from parse_lib import *

CSV_NAME = 'qresults.csv'

if len(sys.argv) != 2:
    print("* [ERROR] need a path!")

logs_path = sys.argv[1]


## Solving Data

print("* get names..")
df_solving = get_names(logs_path)

print("* get result..")
df_solving = df_solving.merge(get_results(logs_path))

print("* get solving times..")
df_solving = df_solving.merge(get_solving_times(logs_path))


## PalRUP data

instances = next(os.walk(logs_path))[1]
instances.sort()
data_per_job = {}

data_blueprint = {INSTANCE_ID: [],
                  RUNTIME_CHECK: [],
                  RUNTIME_VALIDATE: [],
                  SUCCESS_PALRUP: [],
                  RUNTIME_LOCAL_CHECK: [],
                  RUNTIME_REDISTRIBUTE: [],
                  RUNTIME_CONFIRM: [],
                  WAITTIME_LOCAL_CHECK: [],
                  WAITTIME_REDISTRIBUTE: [],
                  WAITTIME_CONFIRM: [],
                  SIZE_PALRUP: [],
                  SIZE_PROXY: [],
                  SIZE_IMPORT: []}

for instance in instances:
    instance_path = f"{logs_path}/{instance}"
    job_paths = glob.glob(f"{instance_path}/palrup_logs.*")
    
    for job_path in job_paths:
        job = job_path.split('.')[-1]

        # check if job's dict exists
        if job not in data_per_job:
            data_per_job[job] = copy.deepcopy(data_blueprint)

        # add meta info
        data_per_job[job][INSTANCE_ID].append(instance)
        data_per_job[job][RUNTIME_CHECK].append(get_checking_time(f"{job_path}/0/palrup.out"))
        data_per_job[job][RUNTIME_VALIDATE].append(get_validation_time(f"{job_path}/pals/0/0.out"))
        data_per_job[job][SUCCESS_PALRUP].append(get_single_success_palrup(job_path))

        pal_data = {RUNTIME_LOCAL_CHECK: [],
                    RUNTIME_REDISTRIBUTE: [],
                    RUNTIME_CONFIRM: [],
                    WAITTIME_LOCAL_CHECK: [],
                    WAITTIME_REDISTRIBUTE: [],
                    WAITTIME_CONFIRM: [],
                    SIZE_PALRUP: [],
                    SIZE_PROXY: [],
                    SIZE_IMPORT: []}

        pals = glob.glob(f"{job_path}/pals/*/*")
        if pals:
            with ThreadPoolExecutor(max_workers=MAX_THREADS) as executor:
                for pal in pals:
                    executor.submit(parse_pal, pal, pal_data)

            data_per_job[job][RUNTIME_LOCAL_CHECK].append(sum(pal_data[RUNTIME_LOCAL_CHECK]) / len(pals))
            data_per_job[job][RUNTIME_REDISTRIBUTE].append(sum(pal_data[RUNTIME_REDISTRIBUTE]) / len(pals))
            data_per_job[job][RUNTIME_CONFIRM].append(sum(pal_data[RUNTIME_CONFIRM]) / len(pals))
                    
            data_per_job[job][SIZE_PALRUP].append(sum(pal_data[SIZE_PALRUP]))
            data_per_job[job][SIZE_PROXY].append(sum(pal_data[SIZE_PROXY]))
            data_per_job[job][SIZE_IMPORT].append(sum(pal_data[SIZE_IMPORT]))
                    
            data_per_job[job][WAITTIME_LOCAL_CHECK].append(sum(pal_data[WAITTIME_LOCAL_CHECK]) / len(pals))
            data_per_job[job][WAITTIME_REDISTRIBUTE].append(sum(pal_data[WAITTIME_REDISTRIBUTE]) / len(pals))
            data_per_job[job][WAITTIME_CONFIRM].append(sum(pal_data[WAITTIME_CONFIRM]) / len(pals))


for job in data_per_job:
    df = pd.DataFrame(data_per_job[job])
    df = df.merge(df_solving, on=INSTANCE_ID)
    df.to_csv(f"{logs_path}/qresults-{job}.csv", index=False)
