
"""
Takes a path to the logs generated by an experimental run and creates a CSV 
containing commonly accessed data for each instance. The created CSV is named 
'qresult.csv' and created in the given directory.
"""

import sys
import pandas as pd
from parse_lib import *

CSV_NAME = 'qresults.csv'

if len(sys.argv) != 2:
    print("* [ERROR] need a path!")

logs_path = sys.argv[1]

# get data
print("* get names..")
df = get_names(logs_path)

print("* get result")
df = df.merge(get_results(logs_path))

print("* get solving times..")
df = df.merge(get_solving_times(logs_path))

print("* get checking times..")
df = df.merge(get_checking_times(logs_path))

print("* get validation times..")
df = df.merge(get_validation_times(logs_path))

print("   * get palrup success..")
df = df.merge(get_success_palrup(logs_path))

print("* get pal info")
df = df.merge(get_full_pal_info(logs_path, verbose=True))

# make .csv of results
print("* make .csv")
df[INSTANCE_ID] = pd.to_numeric(df[INSTANCE_ID])
df.sort_values(by=INSTANCE_ID, inplace=True)
df.to_csv(f"{logs_path}/{CSV_NAME}", sep=' ', index=False)

print("* DONE")
