
#pragma once

// Implements a PalRUP-Tracer library to log PalRUP proof fragments in a clause sharing solver.
// 
// How to use:
//  - create a tracer with palrup_tracer_init() before logging any clasues
//  - Log clauses during runtime with palrup_tracer_log_clause_addition(), palrup_tracer_log_clause_import(), palrup_tracer_log_clause_deletion()
//  - finish proof fragment and free ressources with palrup_tracer_free()

#include <stdbool.h>

struct palrup_tracer;

// Initialize a palrup tracer.
// nb_orig_clauses is only necessary to initialize last_id, which can also be initialized via palrup_tracer_init_last_id() at a later point (before any proof lines are written).
struct palrup_tracer* palrup_tracer_init(const unsigned long nb_orig_clauses, const bool use_binary, const char* fragment_path, const unsigned long solver_id, const unsigned long num_solvers);

// Initializes last_id to next viable ID from initial_id.
// Use with number of clauses in original formula, if tracer has to be initialized before formula is read.
void palrup_tracer_init_last_id(struct palrup_tracer* tracer, unsigned long initial_id);

// Finishes proof fragment and frees allocated ressources.
void palrup_tracer_free(struct palrup_tracer* tracer);

// Returns the last ID that was generated by the tracer.
unsigned long palrup_tracer_last_id(struct palrup_tracer* tracer);

// Returns the tracer's next viable ID. Note that this ID will then never be generated again.
unsigned long palrup_tracer_next_id(struct palrup_tracer* tracer, const int nb_hints, const unsigned long* ext_hints);

// Logs the production of a clause to the tracer's proof fragment.
void palrup_tracer_log_clause_addition(struct palrup_tracer* tracer, const unsigned long id, const int nb_lits, const int* lits, const int nb_hints, const unsigned long* hints);

// Logs the import of a clause to the tracer's proof fragment.
void palrup_tracer_log_clause_import(struct palrup_tracer* tracer, const unsigned long id, const int nb_lits, const int* lits);

// Logs the deletion of a clause to the tracer's proof fragment.
void palrup_tracer_log_clause_deletion(struct palrup_tracer* tracer, const unsigned long id);
