
// MIT License
// 
// (C) 2026 Ruben Götz and Dominik Schreiber, Karlsruhe Institute of Technology
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

#pragma once

// Implements a PalRUP-Tracer library to log PalRUP proof fragments in a clause sharing solver.
// 
// How to use:
//  - create a tracer with palrup_tracer_init() before logging any clasues
//  - Log clauses during runtime with palrup_tracer_log_clause_addition(), palrup_tracer_log_clause_import(), palrup_tracer_log_clause_deletion()
//  - finish proof fragment and free ressources with palrup_tracer_free()

#include <stdbool.h>

struct palrup_tracer;

// Initialize a palrup tracer.
// nb_orig_clauses is only necessary to initialize last_id, which can also be initialized via palrup_tracer_init_last_id() at a later point (before any proof lines are written).
struct palrup_tracer* palrup_tracer_init(const unsigned long nb_orig_clauses, const bool use_binary, const char* fragment_path, const unsigned long solver_id, const unsigned long num_solvers);

// Initializes last_id to next viable ID from initial_id.
// Use with number of clauses in original formula, if tracer has to be initialized before formula is read.
void palrup_tracer_init_last_id(struct palrup_tracer* tracer, unsigned long initial_id);

// Finishes proof fragment and frees allocated ressources.
void palrup_tracer_free(struct palrup_tracer* tracer);

// Returns the last ID that was generated by the tracer.
unsigned long palrup_tracer_last_id(struct palrup_tracer* tracer);

// Returns the tracer's next viable ID. Note that this ID will then never be generated again.
unsigned long palrup_tracer_next_id(struct palrup_tracer* tracer, const int nb_hints, const unsigned long* ext_hints);

// Logs the production of a clause to the tracer's proof fragment.
void palrup_tracer_log_clause_addition(struct palrup_tracer* tracer, const unsigned long id, const int nb_lits, const int* lits, const int nb_hints, const unsigned long* hints);

// Logs the import of a clause to the tracer's proof fragment.
void palrup_tracer_log_clause_import(struct palrup_tracer* tracer, const unsigned long id, const int nb_lits, const int* lits);

// Logs the deletion of a clause to the tracer's proof fragment.
void palrup_tracer_log_clause_deletion(struct palrup_tracer* tracer, const unsigned long id);
