
#ifndef _PalRUPTracer_h
#define _PalRUPTracer_h

// C++ wrapper for the PalRUP-Tracer library to log PalRUP proof fragments in a clause sharing solver
// 
// How to use:
//  - Create PalRUPTracer object
//  - log clauses with log_clause_addition(), log_clause_import(), log_clause_deletion()
//  - proof fragment is only guaranteed to be finished after ~PalRUPTracer() was called

#include <string>
#include <vector>

extern "C" {
    // Define C style PalRUP tracer interface to be used by PalRUPTracer.

    struct palrup_tracer;

    struct palrup_tracer* palrup_tracer_init(const unsigned long nb_orig_clauses, const bool use_binary, const char* fragment_path, const unsigned long solver_id, const unsigned long num_solvers);
    void palrup_tracer_init_last_id(struct palrup_tracer* tracer, unsigned long initial_id);
    void palrup_tracer_free(struct palrup_tracer* tracer);

    unsigned long palrup_tracer_last_id(struct palrup_tracer* tracer);
    unsigned long palrup_tracer_next_id(struct palrup_tracer* tracer, const int nb_hints, const unsigned long* ext_hints);
    void palrup_tracer_log_clause_addition(struct palrup_tracer* tracer, const unsigned long id, const int nb_lits, const int* lits, const int nb_hints, const unsigned long* hints);
    void palrup_tracer_log_clause_import(struct palrup_tracer* tracer, const unsigned long id, const int nb_lits, const int* lits);
    void palrup_tracer_log_clause_deletion(struct palrup_tracer* tracer, const unsigned long id);
}

class PalRUPTracer {
    // C style tracer to be wrapped
    struct palrup_tracer* tracer;

    public:
        
        // Initialize a palrup tracer.
        // nb_orig_clauses is only necessary to initialize last_id, which can also be initialized via palrup_tracer_init_last_id() at a later point (before any proof lines are written).
        PalRUPTracer(const unsigned long nb_orig_clauses,
            const bool use_binary,
            const std::string fragment_path,
            const unsigned long solver_id,
            const unsigned long num_solvers) : tracer(palrup_tracer_init(nb_orig_clauses, use_binary, fragment_path.c_str(), solver_id, num_solvers)) {};

        // Initializes last_id to next viable ID from initial_id.
        // Use with number of clauses in original formula, if tracer has to be initialized before formula is read.
        void init_last_id(unsigned long initial_id) {
            palrup_tracer_init_last_id(this->tracer, initial_id);
        };

        // Finishes proof fragment and frees allocated ressources.
        // Make sure to call destructor to assure that the proof fragment is written in its entirety.
        ~PalRUPTracer() { palrup_tracer_free(this->tracer); };

        // Returns the last ID that was generated by the tracer.
        unsigned long get_last_id() {
            return palrup_tracer_last_id(this->tracer);
        };

        // Returns the tracer's next viable ID. Note that this ID will then never be generated again.
        unsigned long next_id(const int nb_hints, const std::vector<unsigned long> &ext_hints) {
            return palrup_tracer_next_id(this->tracer, nb_hints, ext_hints.data());
        };

        // Logs the production of a clause to the tracer's proof fragment.
        void log_clause_addition(const unsigned long id, const std::vector<int> &lits, const std::vector<unsigned long> &hints) {
            palrup_tracer_log_clause_addition(this->tracer, id, lits.size(), lits.data(), hints.size(), hints.data());
        };

        // Logs the import of a clause to the tracer's proof fragment.
        void log_clause_import(const unsigned long id, const std::vector<int> &lits) {
            palrup_tracer_log_clause_import(this->tracer, id, lits.size(), lits.data());
        };

        // Logs the deletion of a clause to the tracer's proof fragment.
        void log_clause_deletion(const unsigned long id) {
            palrup_tracer_log_clause_deletion(this->tracer, id);
        };
};

#endif
